spring:
  profiles: local
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/coinsdb?zeroDateTimeBehavior=convertToNull
    username: root
    password: rootaccess
    driverClassName: com.mysql.jdbc.Driver
  api:
    client: ck_....
    secret: cs_....
    server: http://<<hostname>>:<<port>>
post-basic-url: http://hostname:port/?post_type=product&#038;p=
csv-separator: ','
fields-per-row: 9
